project = "dataops-terraform"
project_id = "dataops-terraform"
project_number = "370632585880"
region = "us-central1"
zone = "us-central1-a"
gcr_region = "us"
service_name = "config-service"
repository_name = "config-app"
